packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_description = "AMI with Ansible provisioning and security hardening"
  ami_name        = "centos7-ami-${local.timestamp}"
  instance_type   = "t2.micro"
  region          = "us-east-1"
  source_ami      = "ami-0c02fb55956c7d316"
  ssh_username    = "centos"
  ssh_keypair_name = "packer-key"
  ssh_private_key_file = "./packer-key.pem"
  tags = {
    Name = "centos7-ansible"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "../ansible/playbook.yml"
  }

}
