---
- name: Basic CentOS 7.9 provisioning with hardening
  hosts: all
  become: yes

  tasks:

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install basic packages
      yum:
        name:
          - git
          - curl
          - wget
          - unzip
          - vim
        state: present

    - name: Set timezone to Asia/Dhaka (or change to yours)
      timezone:
        name: Asia/Dhaka

    - name: Ensure password authentication is disabled for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Ensure root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Set a custom hostname
      hostname:
        name: centos7-secure-ami

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
