---
- hosts: all
  become: true
  tasks:
    - name: Backup original CentOS-Base.repo
      copy:
        src: /etc/yum.repos.d/CentOS-Base.repo
        dest: /etc/yum.repos.d/CentOS-Base.repo.bak
        remote_src: yes
        force: yes

    - name: Replace CentOS yum repos with vault.centos.org URLs
      copy:
        dest: /etc/yum.repos.d/CentOS-Base.repo
        content: |
          [base]
          name=CentOS-7.9.2009 - Base
          baseurl=http://vault.centos.org/7.9.2009/os/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          [updates]
          name=CentOS-7.9.2009 - Updates
          baseurl=http://vault.centos.org/7.9.2009/updates/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          [extras]
          name=CentOS-7.9.2009 - Extras
          baseurl=http://vault.centos.org/7.9.2009/extras/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          [centosplus]
          name=CentOS-7.9.2009 - Plus
          baseurl=http://vault.centos.org/7.9.2009/centosplus/$basearch/
          gpgcheck=1
          enabled=0
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

    - name: Clean yum metadata
      command: yum clean all

    - name: Rebuild yum cache
      command: yum makecache

    - name: Install essential tools
      yum:
        name:
          - curl
          - wget
          - git
        state: present


