name: Build and Publish AMI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  packer:
    name: Build AMI with Packer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./packer/packer-key.pem
          chmod 600 ./packer/packer-key.pem

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your preferred region

      - name: Run Packer Build (HCL2)
        run: |
          cd packer
          packer init centos7-ami.pkr.hcl
          packer validate centos7-ami.pkr.hcl
          packer build centos7-ami.pkr.hcl
