name: Build and Publish AMI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  packer:
    name: Build AMI with Packer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer plugins
        run: |
          cd packer
          packer init centos7-ami.pkr.hcl

      - name: Validate Packer template
        run: |
          cd packer
          packer validate centos7-ami.pkr.hcl

      - name: Build AMI
        run: |
          cd packer
          packer build centos7-ami.pkr.hcl
